theme: minima
title: legitreview
author: Thatchayani Ravanan
email: info@legitreview.im
url: https://legitreview.in 

description: >
  My first blog. Probably no one else will ever read it, but oh well.
# Minima variables
#twitter_username:  chad_baldwin
github_username:   Dhatchu08
#linkedin_username: chadbaldwin
#dribbble_username: jekyll
facebook_username: Thatchayani Ravanan
#flickr_username: jekyll
instagram_username: legitreview 
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll
rss: rss

show_excerpts: false

# Used by simple links page
social-links:
  LinkedIn:      https://linkedin.com/in/chadbaldwin
  Twitter:       https://twitter.com/chad_baldwin
  Instagram:     https://instagram.com/legitreview 
  GitHub:        https://github.com/dhatchu08
  StackOverflow: https://stackoverflow.com/users/3474677
  Reddit:        https://www.reddit.com/user/chadbaldwin
  Website:       http://legitreview.im
  Facebook:      https://facebook.com/profile.php?id=100014977904147&refsrc=deprecated&_rdr

# plugin: jekyll-seo-tag
twitter:
  username: chad_baldwin
  card: summary_large_image
social:
  name: Thatchayani 
  links:
    - https://twitter.com/chad_baldwin
    - https://www.linkedin.com/in/chadbaldwin
    - https://github.com/dhatchu08

# plugin: jekyll-titles-from-headings
titles_from_headings:
  strip_title: true

collections:
  personal: # collection for personal blog posts
    output: true

header_pages:
  - resume.html
  - archive.html
  - books.md
  - bookmarks.md

plugins:
  - jekyll-feed
  - jekyll-sitemap

google_analytics: UA-185058308-1
gravatar_hash: 2136e716a089f4a3794f4007328c7bfb
code_block_max_height: 500px

home_post_limit: 5

# The github repo that is to be used for looking up comments
comments_repo: chadbaldwin/panni.github.io

defaults:
  - scope:
      path: ""
    values:
      image: https://s.gravatar.com/avatar/2136e716a089f4a3794f4007328c7bfb?s=800 # Apply default site image
  - scope:
      path: ""
      type: posts
    values:
      tags: Other # Add a default tag to all posts

# Disable highlighting to use highlightJS instead
# highlighter: none # Not supported by GitHub Pages
kramdown:
  syntax_highlighter_opts:
    disable: true
